using System;
namespace AzParse;

public static class Region
{
    public static string? ConvertRegionToFriendlyName(this string value)
    {
        return _regionMap.Where(w => w.Key.Contains(value, StringComparison.InvariantCultureIgnoreCase))
            .Select(s => s.Value).FirstOrDefault();
    }

    private static Dictionary<string, string> _regionMap = new()
	{
        { "eastus", "East US" },
        { "eastus2", "East US 2" },
        { "southcentralus", "South Central US" },
        { "westus2", "West US 2" },
        { "westus3", "West US 3" },
        { "australiaeast", "Australia East" },
        { "southeastasia", "Southeast Asia" },
        { "northeurope", "North Europe" },
        { "swedencentral", "Sweden Central" },
        { "uksouth", "UK South" },
        { "westeurope", "West Europe" },
        { "centralus", "Central US" },
        { "southafricanorth", "South Africa North" },
        { "centralindia", "Central India" },
        { "eastasia", "East Asia" },
        { "japaneast", "Japan East" },
        { "koreacentral", "Korea Central" },
        { "canadacentral", "Canada Central" },
        { "francecentral", "France Central" },
        { "germanywestcentral", "Germany West Central" },
        { "norwayeast", "Norway East" },
        { "switzerlandnorth", "Switzerland North" },
        { "uaenorth", "UAE North" },
        { "brazilsouth", "Brazil South" },
        { "eastus2euap", "East US 2 EUAP" },
        { "qatarcentral", "Qatar Central" },
        { "centralusstage", "Central US (Stage)" },
        { "eastusstage", "East US (Stage)" },
        { "eastus2stage", "East US 2 (Stage)" },
        { "northcentralusstage", "North Central US (Stage)" },
        { "southcentralusstage", "South Central US (Stage)" },
        { "westusstage", "West US (Stage)" },
        { "westus2stage", "West US 2 (Stage)" },
        { "asia", "Asia" },
        { "asiapacific", "Asia Pacific" },
        { "australia", "Australia" },
        { "brazil", "Brazil" },
        { "canada", "Canada" },
        { "europe", "Europe" },
        { "france", "France" },
        { "germany", "Germany" },
        { "global", "Global" },
        { "india", "India" },
        { "japan", "Japan" },
        { "korea", "Korea" },
        { "norway", "Norway" },
        { "singapore", "Singapore" },
        { "southafrica", "South Africa" },
        { "switzerland", "Switzerland" },
        { "uae", "United Arab Emirates" },
        { "uk", "United Kingdom" },
        { "unitedstates", "United States" },
        { "unitedstateseuap", "United States EUAP" },
        { "eastasiastage", "East Asia (Stage)" },
        { "southeastasiastage", "Southeast Asia (Stage)" },
        { "eastusstg", "East US STG" },
        { "southcentralusstg", "South Central US STG" },
        { "northcentralus", "North Central US" },
        { "westus ", "West US" },
        { "jioindiawest", "Jio India West" },
        { "centraluseuap", "Central US EUAP" },
        { "westcentralus", "West Central US" },
        { "southafricawest", "South Africa West" },
        { "australiacentral", "Australia Central" },
        { "australiacentral", "Australia Central 2" },
        { "australiasoutheast", "Australia Southeast" },
        { "japanwest", "Japan West" },
        { "jioindiacentral", "Jio India Central" },
        { "koreasouth", "Korea South" },
        { "southindia", "South India" },
        { "westindia", "West India" },
        { "canadaeast", "Canada East" },
        { "francesouth", "France South" },
        { "germanynorth", "Germany North" },
        { "norwaywest", "Norway West" },
        { "switzerlandwest", "Switzerland West" },
        { "ukwest", "UK West" },
        { "uaecentral", "UAE Central" },
        { "brazilsoutheast", "Brazil Southeast" }
    };
}