using System;
namespace AzParse;

public static class Resources
{
    public static string? ConvertResourceToFriendlyName(this string value)
    {
        return _resourceMap.Where(w => w.Key.Contains(value, StringComparison.InvariantCultureIgnoreCase))
            .Select(s => s.Value).FirstOrDefault();
    }

    private static Dictionary<string, string> _resourceMap = new()
    {
        { "Microsoft.AAD", "Azure Active Directory Domain Services" },
        { "Microsoft.Addons", "Core" },
        { "Microsoft.App", "Azure Container App" },
        { "Microsoft.ADHybridHealthService", "Azure Active Directory" },
        { "Microsoft.Advisor", "Azure Advisor" },
        { "Microsoft.AlertsManagement", "Azure Monitor" },
        { "Microsoft.AnalysisServices", "Azure Analysis Services" },
        { "Microsoft.ApiManagement", "API Management" },
        { "Microsoft.AppConfiguration", "Azure App Configuration" },
        { "Microsoft.AppPlatform", "Azure Spring Apps" },
        { "Microsoft.Attestation", "Azure Attestation Service" },
        { "Microsoft.Authorization", "Azure Resource Manager" },
        { "Microsoft.Automation", "Azure Automation" },
        { "Microsoft.AutonomousSystems", "Autonomous Systems" },
        { "Microsoft.AVS", "Azure VMware Solution" },
        { "Microsoft.AzureActiveDirectory", "Azure Active Directory B2C" },
        { "Microsoft.AzureArcData", "Azure Arc-enabled Data Services" },
        { "Microsoft.AzureData", "Azure Data Registry" },
        { "Microsoft.AzureStack", "Core" },
        { "Microsoft.AzureStackHCI", "Azure Stack HCI" },
        { "Microsoft.Batch", "Azure Batch" },
        { "Microsoft.Billing", "Cost Management and Billing" },
        { "Microsoft.BingMaps", "Bing Maps" },
        { "Microsoft.Blockchain", "Azure Blockchain Service" },
        { "Microsoft.BlockchainTokens", "Azure Blockchain Tokens" },
        { "Microsoft.Blueprint", "Azure Blueprints" },
        { "Microsoft.BotService", "Azure Bot Service" },
        { "Microsoft.Cache", "Azure Cache for Redis" },
        { "Microsoft.Capacity", "Core" },
        { "Microsoft.Cdn", "Content Delivery Network" },
        { "Microsoft.CertificateRegistration", "App Service Certificates" },
        { "Microsoft.ChangeAnalysis", "Azure Monitor" },
        { "Microsoft.CognitiveServices", "Cognitive Services" },
        { "Microsoft.Compute/virtualMachines", "Virtual Machines" },
        { "Microsoft.Compute/virtualMachineScaleSets", "Virtual Machine Scale Set" },
        { "Microsoft.ContainerInstance", "Container Instances" },
        { "Microsoft.ContainerRegistry", "Container Registry" },
        { "Microsoft.ContainerService", "Azure Kubernetes Service" },
        { "Microsoft.CustomerLockbox", "Customer Lockbox for Microsoft Azure" },
        { "Microsoft.CustomProviders", "Azure Custom Providers" },
        { "Microsoft.DataBox", "Azure Data Box" },
        { "Microsoft.DataBoxEdge", "Azure Stack Edge" },
        { "Microsoft.Databricks", "Azure Databricks" },
        { "Microsoft.DataCatalog", "Data Catalog" },
        { "Microsoft.DataFactory", "Data Factory" },
        { "Microsoft.DataLakeAnalytics", "Data Lake Analytics" },
        { "Microsoft.DataLakeStore", "Azure Data Lake Storage Gen2" },
        { "Microsoft.DataMigration", "Azure Database Migration Service" },
        { "Microsoft.DataProtection", "Data Protection" },
        { "Microsoft.DataShare", "Azure Data Share" },
        { "Microsoft.DBforMariaDB", "Azure Database for MariaDB" },
        { "Microsoft.DBforMySQL", "Azure Database for MySQL" },
        { "Microsoft.DBforPostgreSQL", "Azure Database for PostgreSQL" },
        { "Microsoft.DesktopVirtualization", "Azure Virtual Desktop" },
        { "Microsoft.Devices/IotHubs", "Azure IoT Hub" },
        { "Microsoft.Devices/ProvisioningServices", "Azure IoT Hub Device Provisioning Service" },
        { "Microsoft.DeviceUpdate", "Device Update for IoT Hub" },
        { "Microsoft.DevOps", "Azure DevOps" },
        { "Microsoft.DevSpaces", "Azure Dev Spaces" },
        { "Microsoft.DevTestLab", "Azure Lab Services" },
        { "Microsoft.DigitalTwins", "Azure Digital Twins" },
        { "Microsoft.DocumentDB", "Azure Cosmos DB" },
        { "Microsoft.DomainRegistration", "App Service" },
        { "Microsoft.EnterpriseKnowledgeGraph", "Enterprise Knowledge Graph" },
        { "Microsoft.EventGrid", "Event Grid" },
        { "Microsoft.EventHub", "Event Hub" },
        { "Microsoft.GuestConfiguration", "Azure Policy" },
        { "Microsoft.HanaOnAzure", "SAP HANA on Azure Large Instances" },
        { "Microsoft.HardwareSecurityModules", "Azure Dedicated HSM" },
        { "Microsoft.HDInsight", "HDInsight" },
        { "Microsoft.HealthcareApis", "Azure API for FHIR" },
        { "Microsoft.HybridCompute", "Azure Arc-enabled servers" },
        { "Microsoft.HybridData", "StorSimple" },
        { "Microsoft.HybridNetwork", "Network Function Manager" },
        { "Microsoft.Insights", "Azure Monitor" },
        { "Microsoft.IoTCentral", "Azure IoT Central" },
        { "Microsoft.IoTSpaces", "Azure Digital Twins" },
        { "Microsoft.KeyVault", "Key Vault" },
        { "Microsoft.Kubernetes", "Azure Arc-enabled Kubernetes" },
        { "Microsoft.KubernetesConfiguration", "Azure Arc-enabled Kubernetes" },
        { "Microsoft.Kusto", "Azure Data Explorer" },
        { "Microsoft.LabServices", "Azure Lab Services" },
        { "Microsoft.Logic", "Logic Apps" },
        { "Microsoft.MachineLearning", "Machine Learning Studio" },
        { "Microsoft.MachineLearningServices", "Azure Machine Learning" },
        { "Microsoft.Maintenance", "Azure Maintenance" },
        { "Microsoft.ManagedIdentity", "Managed identities for Azure resources" },
        { "Microsoft.ManagedNetwork", "PaaS Managed Network" },
        { "Microsoft.ManagedServices", "Azure Lighthouse" },
        { "Microsoft.Management", "Management Groups" },
        { "Microsoft.Maps", "Azure Maps" },
        { "Microsoft.Media", "Media Services" },
        { "Microsoft.Microservices4Spring", "Azure Spring Apps" },
        { "Microsoft.Migrate", "Azure Migrate" },
        { "Microsoft.MixedReality", "Azure Spatial Anchors" },
        { "Microsoft.MobileNetwork", "Azure Private 5G Core" },
        { "Microsoft.NetApp", "Azure NetApp Files" },
        { "Microsoft.Network/applicationGateways", "Application Gateway" },
        { "Microsoft.Network/bastionHosts", "Azure Bastion" },
        { "Microsoft.Network/ddosCustomPolicies", "Azure DDoS Protection" },
        { "Microsoft.Network/ddosProtectionPlans", "Azure DDoS Protection" },
        { "Microsoft.Network/dnszones", "Azure DNS" },
        { "Microsoft.Network/expressRouteCircuits", "Azure ExpressRoute" },
        { "Microsoft.Network/firewallPolicies", "Azure Firewall" },
        { "Microsoft.Network/frontdoors", "Azure Front Door" },
        { "Microsoft.Network/privateLinkServices", "Azure Private Link Service" },
        { "Microsoft.Network/loadBalancers", "Load Balancer" },
        { "Microsoft.Network/localNetworkGateways", "Local Network Gateway" },
        { "Microsoft.Network/natGateways", "NAT Gateway" },
        { "Microsoft.Network/networkInterfaces", "Network Interface" },
        { "Microsoft.Network/networkProfiles", "Network Profile" },
        { "Microsoft.Network/networkSecurityGroups", "Network Security Group" },
        { "Microsoft.Network/networkVirtualAppliances", "Network Virtual Appliance" },
        { "Microsoft.Network/networkWatchers", "Network Watcher" },
        { "Microsoft.Network/privateDnsZones", "Private DNS Zone" },
        { "Microsoft.Network/privateEndpoints", "Private Endpoints" },
        { "Microsoft.Network/publicIPAddresses", "Public IP Address" },
        { "Microsoft.Network/routeTable", "Route Table" },
        { "Microsoft.Network/trafficmanagerprofiles", "Traffic Manager Profile" },
        { "Microsoft.Network/virtualNetworkGateways", "Virtual Network Gateway" },
        { "Microsoft.Network/virtualNetworks", "Virtual Network" },
        { "Microsoft.Network/virtualRouters", "Virtual Router" },
        { "Microsoft.Network/virtualWans", "Virtual WAN" },
        { "Microsoft.Network/vpnGateways", "VPN Gateway" },
        { "Microsoft.Network/vpnServerConfigurations", "VPN Configuration" },
        { "Microsoft.Network/vpnSites", "VPN Site" },
        { "Microsoft.Notebooks", "Azure Notebooks" },
        { "Microsoft.NotificationHubs", "Notification Hub" },
        { "Microsoft.ObjectStore", "Object Store" },
        { "Microsoft.OffAzure", "Azure Migrate" },
        { "Microsoft.OperationalInsights", "Azure Monitor" },
        { "Microsoft.OperationsManagement", "Azure Monitor" },
        { "Microsoft.Peering", "Azure Peering Service" },
        { "Microsoft.PolicyInsights", "Azure Policy" },
        { "Microsoft.PowerBI", "Power BI" },
        { "Microsoft.PowerBIDedicated", "Power BI Embedded" },
        { "Microsoft.PowerPlatform", "Power Platform" },
        { "Microsoft.ProjectBabylon", "Azure Data Catalog" },
        { "Microsoft.Quantum", "Azure Quantum" },
        { "Microsoft.RecoveryServices", "Azure Site Recovery" },
        { "Microsoft.RedHatOpenShift", "Azure Red Hat OpenShift" },
        { "Microsoft.Relay", "Azure Relay" },
        { "Microsoft.ResourceGraph", "Azure Resource Graph" },
        { "Microsoft.ResourceHealth", "Azure Service Health" },
        { "Microsoft.Scheduler", "Scheduler" },
        { "Microsoft.Search", "Azure Cognitive Search" },
        { "Microsoft.Security", "Security Center" },
        { "Microsoft.SecurityInsights", "Microsoft Sentinel" },
        { "Microsoft.ServiceBus", "Service Bus" },
        { "Microsoft.ServiceFabric", "Service Fabric" },
        { "Microsoft.SignalRService", "Azure SignalR Service" },
        { "Microsoft.Solutions", "Azure Managed Applications" },
        { "Microsoft.Sql/managedInstances", "SQL Managed Instance" },
        { "Microsoft.Sql/servers", "Azure SQL Server" },
        { "Microsoft.Sql/servers/elasticpools", "Azure SQL Server Elastic Pool" },
        { "Microsoft.SqlVirtualMachine", "SQL Server on Azure Virtual Machines" },
        { "Microsoft.Storage", "Storage" },
        { "Microsoft.StorageCache", "Azure HPC Cache" },
        { "Microsoft.StorageSync", "Storage" },
        { "Microsoft.StorSimple", "StorSimple" },
        { "Microsoft.StreamAnalytics", "Azure Stream Analytics" },
        { "Microsoft.Synapse", "Azure Synapse Analytics" },
        { "Microsoft.TimeSeriesInsights", "Azure Time Series Insights" },
        { "Microsoft.VirtualMachineImages", "Azure Image Builder" },
        { "microsoft.visualstudio", "Azure DevOps" },
        { "Microsoft.VMware", "Azure VMware Solution" },
        { "Microsoft.VSOnline", "Azure DevOps" },
        { "Microsoft.Web/serverFarms", "App Service Plan" },
        { "Microsoft.Web/sites", "Web App" },
        { "Microsoft.Web/staticSites", "Azure Static Web Apps" },
        { "Microsoft.WorkloadMonitor", "Azure Monitor" }
    };
}